name: Build AIX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Ant
        run: sudo apt-get install -y ant

      - name: Compile Extension
        run: |
          ant build

      - name: Upload AIX
        uses: actions/upload-artifact@v3
        with:
          name: Base64FileEncoder
          path: build/extensions/Base64FileEncoder.aix
